// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyCrack(arg1) {
  return window['go']['main']['App']['ApplyCrack'](arg1);
}

export function CheckApp() {
  return window['go']['main']['App']['CheckApp']();
}

export function DownloadVersion(arg1) {
  return window['go']['main']['App']['DownloadVersion'](arg1);
}

export function GetCleanupStatus() {
  return window['go']['main']['App']['GetCleanupStatus']();
}

export function GetCrackStatus() {
  return window['go']['main']['App']['GetCrackStatus']();
}

export function GetDebugInfo() {
  return window['go']['main']['App']['GetDebugInfo']();
}

export function GetInstallationInfo() {
  return window['go']['main']['App']['GetInstallationInfo']();
}

export function GetLockedVersion() {
  return window['go']['main']['App']['GetLockedVersion']();
}

export function GetVersions() {
  return window['go']['main']['App']['GetVersions']();
}

export function IsLocked() {
  return window['go']['main']['App']['IsLocked']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RunCleanup() {
  return window['go']['main']['App']['RunCleanup']();
}

export function SetLock(arg1, arg2) {
  return window['go']['main']['App']['SetLock'](arg1, arg2);
}
