// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {commands} from '../models';

export function ApplyCrack(arg1:boolean):Promise<void>;

export function CheckApp():Promise<commands.AppInfo>;

export function DownloadVersion(arg1:string):Promise<void>;

export function GetCleanupStatus():Promise<commands.CleanupResult>;

export function GetCrackStatus():Promise<commands.CrackStatus>;

export function GetDebugInfo():Promise<Record<string, string>>;

export function GetInstallationInfo():Promise<commands.InstallationInfo>;

export function GetLockedVersion():Promise<string>;

export function GetVersions():Promise<Array<commands.Version>>;

export function IsLocked():Promise<boolean>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function RunCleanup():Promise<commands.CleanupResult>;

export function SetLock(arg1:boolean,arg2:string):Promise<void>;
